In [3]:
import pandas as pd

data = pd.read_csv("Prices.csv")

In [4]:
data = pd.DataFrame(data)
data

,TexmacoRail,CentralBank,KothariSugar,PCBL,GreavesCotton,PadamjiPaper,Time
0,136.45,37.60,55.6,161.20,138.1,47.75,2023-09-13 09:11:41.093625
1,136.45,37.60,55.6,161.30,138.1,48.70,2023-09-13 09:17:55.361090
2,136.45,37.60,55.6,161.30,138.1,48.70,2023-09-13 09:19:54.677369
3,136.45,37.60,55.6,161.30,138.1,48.70,2023-09-13 09:20:09.294568
4,137.70,38.25,55.6,161.30,140.8,48.70,2023-09-13 09:36:59.441768
5,137.70,38.25,55.6,164.40,140.8,48.70,2023-09-13 09:37:34.717540
6,137.70,38.25,55.6,164.40,140.8,48.70,2023-09-13 09:38:49.565885
7,137.70,38.25,55.6,164.40,140.8,48.70,2023-09-13 09:39:23.790586
8,141.95,38.25,55.6,164.40,140.8,48.70,2023-09-13 09:41:35.853012
9,141.95,38.25,53.1,164.40,140.8,48.35,2023-09-13 09:44:04.238323
10,133.15,38.00,55.0,164.25,139.7,50.15,2023-09-13 11:59:11.142654